# Generated by Django 3.1.5 on 2021-02-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
