# Generated by Django 3.1.5 on 2021-02-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0002_delete_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('howLong', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('time', models.TimeField(verbose_name='Workout Time')),
            ],
        ),
    ]
